language: node_js
node_js:
  - "iojs"

branches:
  only:
    - master

script: make

env:
  global:
    - GH_REF: github.com/stryju/today.git
    - secure: WB38qZm+z7uHiG778RnsLmQ9bO0+666rFskZFZxYer+k2Q+Jx3m7aX1SdoXip1663KXLCR/lAtSpotPjqlFyM8ztKuZ8VKreQMagbjnIkfb74Ph9A0DDYAbSKsawxXs88CGW9DSgOJ5jbxTnQRLFUlezXvYcy0EbdRDCaMG1DBDCQQdJBctPWz0uzR04C+yVpTeArsv3eSKP7yZPFxZyu4kvb6SKJLxdsXh07urzpGSq3NdVXHWS/sALq7uVfsy5RZxKUjm269/USyAlNxYuj80YGLp65YaSJhH47lCFC8RaA2bc6kFCVqb7+nHkwsZ17p6frC5TiwbBSZENTJ83SzWtugXD+xCKvp5qdesVYHmiWtbSAquHujm9V9QyEuUEukLHBr9wzATRyELAExrdUgiymvNjccYLrR+Ud08bUsxVU3qoe2sbCXcAVyKxH5Gq0hLj0mnpeRThR8iGm6H9OXXlOpv34jz8gvRoTS7bL+1renqFDxQXJGMyKca2hit9+14UlF1dr0whihnB9LKhrDcXLob3OIo7n4D9Eum1YLmnWtoGLAJlZY7RkdTetyPCetjPauRmaFpFHM/kF+KAsE7wRf4d3qXNFvFCxEYCbM2NEPuxIMgFYr/Neg/EhQczSsHDmlQh9QB59CwrQLZuIp1+dEFlDWK1P5M1NtUT5mw=
